-- ============================================================================
-- BG Session — migration 0065: seed 500 most-popular board games beyond the top 1000
--
-- Follows migration 0064 (BGG Top 1000 by rank). These are the 500 MOST-RATED
-- games on BoardGameGeek (usersrated, a popularity proxy) that are NOT already in
-- the catalog — i.e. mainstream/popular titles that sit below rank 1000 (Monopoly,
-- Risk, Munchkin, Exploding Kittens, Forbidden Island, ...) plus popular expansions.
--
-- Source & verification (same rigor as 0064): candidate ordering from the BGG
-- ranks data dump (usersrated), then every game re-verified one-by-one against
-- BoardGameGeek's authoritative item API (api.geekdo.com): exact primary name (no
-- year), exact canonical boardgamegeek.com/boardgame/<id>/<slug> URL, and base vs
-- expansion from each item's BGG subtype. Rows here: 417 base, 83 expansion.
--
-- board_games.name is UNIQUE and the app-wide identity key, so any candidate whose
-- name already exists in the catalog was skipped (e.g. other editions of Love
-- Letter, Citadels, Puerto Rico, Castles of Burgundy, and already-seeded expansions
-- like Catan: Seafarers). Every name below is new and distinct.
--
-- Upsert (idempotent): on name conflict, refresh bgg_url + category.
-- ============================================================================

insert into board_games (name, category, bgg_url) values
  ('Forbidden Island', 'base', 'https://boardgamegeek.com/boardgame/65244/forbidden-island'),
  ('Munchkin', 'base', 'https://boardgamegeek.com/boardgame/1927/munchkin'),
  ('Exploding Kittens', 'base', 'https://boardgamegeek.com/boardgame/172225/exploding-kittens'),
  ('Monopoly', 'base', 'https://boardgamegeek.com/boardgame/1406/monopoly'),
  ('Risk', 'base', 'https://boardgamegeek.com/boardgame/181/risk'),
  ('The Mind', 'base', 'https://boardgamegeek.com/boardgame/244992/the-mind'),
  ('Saboteur', 'base', 'https://boardgamegeek.com/boardgame/9220/saboteur'),
  ('Machi Koro', 'base', 'https://boardgamegeek.com/boardgame/143884/machi-koro'),
  ('Scrabble', 'base', 'https://boardgamegeek.com/boardgame/320/scrabble'),
  ('BANG!', 'base', 'https://boardgamegeek.com/boardgame/3955/bang'),
  ('UNO', 'base', 'https://boardgamegeek.com/boardgame/2223/uno'),
  ('Cards Against Humanity', 'base', 'https://boardgamegeek.com/boardgame/50381/cards-against-humanity'),
  ('Tsuro', 'base', 'https://boardgamegeek.com/boardgame/16992/tsuro'),
  ('Smash Up', 'base', 'https://boardgamegeek.com/boardgame/122522/smash-up'),
  ('Carcassonne: Inns & Cathedrals', 'expansion', 'https://boardgamegeek.com/boardgame/2993/carcassonne-inns-and-cathedrals'),
  ('Hey, That''s My Fish!', 'base', 'https://boardgamegeek.com/boardgame/8203/hey-thats-my-fish'),
  ('Clue', 'base', 'https://boardgamegeek.com/boardgame/1294/clue'),
  ('Spyfall', 'base', 'https://boardgamegeek.com/boardgame/166384/spyfall'),
  ('Guillotine', 'base', 'https://boardgamegeek.com/boardgame/116/guillotine'),
  ('Spot it!', 'base', 'https://boardgamegeek.com/boardgame/63268/spot-it'),
  ('Qwirkle', 'base', 'https://boardgamegeek.com/boardgame/25669/qwirkle'),
  ('Concept', 'base', 'https://boardgamegeek.com/boardgame/147151/concept'),
  ('Rummikub', 'base', 'https://boardgamegeek.com/boardgame/811/rummikub'),
  ('Catan: Cities & Knights', 'expansion', 'https://boardgamegeek.com/boardgame/926/catan-cities-and-knights'),
  ('Apples to Apples', 'base', 'https://boardgamegeek.com/boardgame/74/apples-to-apples'),
  ('Zombie Dice', 'base', 'https://boardgamegeek.com/boardgame/62871/zombie-dice'),
  ('Fluxx', 'base', 'https://boardgamegeek.com/boardgame/258/fluxx'),
  ('Pandemic: On the Brink', 'expansion', 'https://boardgamegeek.com/boardgame/40849/pandemic-on-the-brink'),
  ('Boss Monster: The Dungeon Building Card Game', 'base', 'https://boardgamegeek.com/boardgame/131835/boss-monster-the-dungeon-building-card-game'),
  ('Scotland Yard', 'base', 'https://boardgamegeek.com/boardgame/438/scotland-yard'),
  ('Carcassonne: Traders & Builders', 'expansion', 'https://boardgamegeek.com/boardgame/5405/carcassonne-traders-and-builders'),
  ('Catan: 5-6 Player Expansion', 'expansion', 'https://boardgamegeek.com/boardgame/2807/catan-5-6-player-expansion'),
  ('Wingspan: European Expansion', 'expansion', 'https://boardgamegeek.com/boardgame/290448/wingspan-european-expansion'),
  ('Yahtzee', 'base', 'https://boardgamegeek.com/boardgame/2243/yahtzee'),
  ('Stratego', 'base', 'https://boardgamegeek.com/boardgame/1917/stratego'),
  ('Jenga', 'base', 'https://boardgamegeek.com/boardgame/2452/jenga'),
  ('King of New York', 'base', 'https://boardgamegeek.com/boardgame/160499/king-of-new-york'),
  ('Castle Panic', 'base', 'https://boardgamegeek.com/boardgame/43443/castle-panic'),
  ('Cockroach Poker', 'base', 'https://boardgamegeek.com/boardgame/11971/cockroach-poker'),
  ('Gloom', 'base', 'https://boardgamegeek.com/boardgame/12692/gloom'),
  ('Ca$h ''n Guns: Second Edition', 'base', 'https://boardgamegeek.com/boardgame/155362/ca-dollar-h-n-guns-second-edition'),
  ('7 Wonders Duel: Pantheon', 'expansion', 'https://boardgamegeek.com/boardgame/202976/7-wonders-duel-pantheon'),
  ('The Lord of the Rings', 'base', 'https://boardgamegeek.com/boardgame/823/the-lord-of-the-rings'),
  ('Dominion: Seaside', 'expansion', 'https://boardgamegeek.com/boardgame/51811/dominion-seaside'),
  ('Talisman: Revised 4th Edition', 'base', 'https://boardgamegeek.com/boardgame/27627/talisman-revised-4th-edition'),
  ('Labyrinth', 'base', 'https://boardgamegeek.com/boardgame/1219/labyrinth'),
  ('Zooloretto', 'base', 'https://boardgamegeek.com/boardgame/27588/zooloretto'),
  ('Dominion: Prosperity', 'expansion', 'https://boardgamegeek.com/boardgame/66690/dominion-prosperity'),
  ('Zombies!!!', 'base', 'https://boardgamegeek.com/boardgame/2471/zombies'),
  ('Backgammon', 'base', 'https://boardgamegeek.com/boardgame/2397/backgammon'),
  ('7 Wonders: Leaders', 'expansion', 'https://boardgamegeek.com/boardgame/92539/7-wonders-leaders'),
  ('Hive Pocket', 'base', 'https://boardgamegeek.com/boardgame/154597/hive-pocket'),
  ('Welcome to the Dungeon', 'base', 'https://boardgamegeek.com/boardgame/150312/welcome-to-the-dungeon'),
  ('Lords of Waterdeep: Scoundrels of Skullport', 'expansion', 'https://boardgamegeek.com/boardgame/134342/lords-of-waterdeep-scoundrels-of-skullport'),
  ('Catan Card Game', 'base', 'https://boardgamegeek.com/boardgame/278/catan-card-game'),
  ('Jungle Speed', 'base', 'https://boardgamegeek.com/boardgame/8098/jungle-speed'),
  ('Last Night on Earth: The Zombie Game', 'base', 'https://boardgamegeek.com/boardgame/29368/last-night-on-earth-the-zombie-game'),
  ('The Game of Life', 'base', 'https://boardgamegeek.com/boardgame/2921/game-of-life'),
  ('SET', 'base', 'https://boardgamegeek.com/boardgame/1198/set'),
  ('Taboo', 'base', 'https://boardgamegeek.com/boardgame/1111/taboo'),
  ('Quarriors!', 'base', 'https://boardgamegeek.com/boardgame/91536/quarriors'),
  ('The Game', 'base', 'https://boardgamegeek.com/boardgame/173090/the-game'),
  ('Bananagrams', 'base', 'https://boardgamegeek.com/boardgame/27225/bananagrams'),
  ('Pick-omino', 'base', 'https://boardgamegeek.com/boardgame/15818/pick-omino'),
  ('One Deck Dungeon', 'base', 'https://boardgamegeek.com/boardgame/179275/one-deck-dungeon'),
  ('Monopoly Deal Card Game', 'base', 'https://boardgamegeek.com/boardgame/40398/monopoly-deal-card-game'),
  ('The Werewolves of Miller''s Hollow', 'base', 'https://boardgamegeek.com/boardgame/25821/the-werewolves-of-millers-hollow'),
  ('Scythe: Invaders from Afar', 'expansion', 'https://boardgamegeek.com/boardgame/199727/scythe-invaders-from-afar'),
  ('Sequence', 'base', 'https://boardgamegeek.com/boardgame/2375/sequence'),
  ('Roll Through the Ages: The Bronze Age', 'base', 'https://boardgamegeek.com/boardgame/37380/roll-through-the-ages-the-bronze-age'),
  ('ICECOOL', 'base', 'https://boardgamegeek.com/boardgame/177524/icecool'),
  ('Rhino Hero', 'base', 'https://boardgamegeek.com/boardgame/91514/rhino-hero'),
  ('Battleship', 'base', 'https://boardgamegeek.com/boardgame/2425/battleship'),
  ('Poker', 'base', 'https://boardgamegeek.com/boardgame/1115/poker'),
  ('Phase 10', 'base', 'https://boardgamegeek.com/boardgame/1258/phase-10'),
  ('King of Tokyo: Power Up!', 'expansion', 'https://boardgamegeek.com/boardgame/127067/king-of-tokyo-power-up'),
  ('Lanterns: The Harvest Festival', 'base', 'https://boardgamegeek.com/boardgame/160851/lanterns-the-harvest-festival'),
  ('Terraforming Mars: Hellas & Elysium', 'expansion', 'https://boardgamegeek.com/boardgame/218127/terraforming-mars-hellas-and-elysium'),
  ('Viticulture: Tuscany Essential Edition', 'expansion', 'https://boardgamegeek.com/boardgame/202174/viticulture-tuscany-essential-edition'),
  ('Unstable Unicorns', 'base', 'https://boardgamegeek.com/boardgame/234190/unstable-unicorns'),
  ('The Castles of Burgundy: Special Edition', 'base', 'https://boardgamegeek.com/boardgame/363622/the-castles-of-burgundy-special-edition'),
  ('5-Minute Dungeon', 'base', 'https://boardgamegeek.com/boardgame/207830/5-minute-dungeon'),
  ('Ticket to Ride: USA 1910', 'expansion', 'https://boardgamegeek.com/boardgame/24439/ticket-to-ride-usa-1910'),
  ('Scattergories', 'base', 'https://boardgamegeek.com/boardgame/2381/scattergories'),
  ('Axis & Allies', 'base', 'https://boardgamegeek.com/boardgame/98/axis-and-allies'),
  ('7 Wonders: Cities', 'expansion', 'https://boardgamegeek.com/boardgame/111661/7-wonders-cities'),
  ('Mascarade', 'base', 'https://boardgamegeek.com/boardgame/139030/mascarade'),
  ('Carcassonne: The River', 'expansion', 'https://boardgamegeek.com/boardgame/2591/carcassonne-the-river'),
  ('Exploding Kittens: NSFW Edition', 'base', 'https://boardgamegeek.com/boardgame/172242/exploding-kittens-nsfw-edition'),
  ('Ghost Blitz', 'base', 'https://boardgamegeek.com/boardgame/83195/ghost-blitz'),
  ('Condottiere', 'base', 'https://boardgamegeek.com/boardgame/112/condottiere'),
  ('Thunderstone', 'base', 'https://boardgamegeek.com/boardgame/53953/thunderstone'),
  ('Carcassonne: Dragon & Fairy', 'expansion', 'https://boardgamegeek.com/boardgame/15158/carcassonne-dragon-and-fairy'),
  ('Ca$h ''n Gun$', 'base', 'https://boardgamegeek.com/boardgame/19237/ca-dollar-h-n-gun-dollar'),
  ('Connect Four', 'base', 'https://boardgamegeek.com/boardgame/2719/connect-four'),
  ('Ubongo', 'base', 'https://boardgamegeek.com/boardgame/16986/ubongo'),
  ('L.L.A.M.A.', 'base', 'https://boardgamegeek.com/boardgame/266083/llama'),
  ('Kahuna', 'base', 'https://boardgamegeek.com/boardgame/394/kahuna'),
  ('Pit', 'base', 'https://boardgamegeek.com/boardgame/140/pit'),
  ('Morels', 'base', 'https://boardgamegeek.com/boardgame/122298/morels'),
  ('Race for the Galaxy: The Gathering Storm', 'expansion', 'https://boardgamegeek.com/boardgame/34499/race-for-the-galaxy-the-gathering-storm'),
  ('Cranium', 'base', 'https://boardgamegeek.com/boardgame/891/cranium'),
  ('Skip-Bo', 'base', 'https://boardgamegeek.com/boardgame/1269/skip-bo'),
  ('Loopin'' Louie', 'base', 'https://boardgamegeek.com/boardgame/327/loopin-louie'),
  ('Dune: Imperium – Rise of Ix', 'expansion', 'https://boardgamegeek.com/boardgame/342031/dune-imperium-rise-of-ix'),
  ('Quoridor', 'base', 'https://boardgamegeek.com/boardgame/624/quoridor'),
  ('Red Rising', 'base', 'https://boardgamegeek.com/boardgame/329465/red-rising'),
  ('Checkers', 'base', 'https://boardgamegeek.com/boardgame/2083/checkers'),
  ('Lost Ruins of Arnak: Expedition Leaders', 'expansion', 'https://boardgamegeek.com/boardgame/341254/lost-ruins-of-arnak-expedition-leaders'),
  ('Dungeons & Dragons: Castle Ravenloft Board Game', 'base', 'https://boardgamegeek.com/boardgame/59946/dungeons-and-dragons-castle-ravenloft-board-game'),
  ('Age of War', 'base', 'https://boardgamegeek.com/boardgame/28086/age-of-war'),
  ('Flick ''em Up!', 'base', 'https://boardgamegeek.com/boardgame/169124/flick-em-up'),
  ('XCOM: The Board Game', 'base', 'https://boardgamegeek.com/boardgame/163602/xcom-the-board-game'),
  ('Root: The Riverfolk Expansion', 'expansion', 'https://boardgamegeek.com/boardgame/241386/root-the-riverfolk-expansion'),
  ('BANG! The Bullet!', 'base', 'https://boardgamegeek.com/boardgame/30933/bang-the-bullet'),
  ('The Red Dragon Inn', 'base', 'https://boardgamegeek.com/boardgame/24310/the-red-dragon-inn'),
  ('Elfenland', 'base', 'https://boardgamegeek.com/boardgame/10/elfenland'),
  ('Here to Slay', 'base', 'https://boardgamegeek.com/boardgame/299252/here-to-slay'),
  ('Othello', 'base', 'https://boardgamegeek.com/boardgame/2389/othello'),
  ('Shadow Hunters', 'base', 'https://boardgamegeek.com/boardgame/24068/shadow-hunters'),
  ('Once Upon a Time: The Storytelling Card Game', 'base', 'https://boardgamegeek.com/boardgame/1234/once-upon-a-time-the-storytelling-card-game'),
  ('Animal Upon Animal', 'base', 'https://boardgamegeek.com/boardgame/17329/animal-upon-animal'),
  ('Terraforming Mars: Venus Next', 'expansion', 'https://boardgamegeek.com/boardgame/231965/terraforming-mars-venus-next'),
  ('CuBirds', 'base', 'https://boardgamegeek.com/boardgame/245476/cubirds'),
  ('Mr. Jack Pocket', 'base', 'https://boardgamegeek.com/boardgame/72287/mr-jack-pocket'),
  ('Niagara', 'base', 'https://boardgamegeek.com/boardgame/13308/niagara'),
  ('Mille Bornes', 'base', 'https://boardgamegeek.com/boardgame/590/mille-bornes'),
  ('Fairy Tale', 'base', 'https://boardgamegeek.com/boardgame/13823/fairy-tale'),
  ('Eight-Minute Empire', 'base', 'https://boardgamegeek.com/boardgame/131366/eight-minute-empire'),
  ('Boggle', 'base', 'https://boardgamegeek.com/boardgame/1293/boggle'),
  ('Taco Cat Goat Cheese Pizza', 'base', 'https://boardgamegeek.com/boardgame/253664/taco-cat-goat-cheese-pizza'),
  ('Dominion: Alchemy', 'expansion', 'https://boardgamegeek.com/boardgame/66098/dominion-alchemy'),
  ('Quarto', 'base', 'https://boardgamegeek.com/boardgame/681/quarto'),
  ('Cottage Garden', 'base', 'https://boardgamegeek.com/boardgame/204027/cottage-garden'),
  ('Fallout', 'base', 'https://boardgamegeek.com/boardgame/232918/fallout'),
  ('Timeline: Inventions', 'base', 'https://boardgamegeek.com/boardgame/85256/timeline-inventions'),
  ('The Great Dalmuti', 'base', 'https://boardgamegeek.com/boardgame/929/the-great-dalmuti'),
  ('Fog of Love', 'base', 'https://boardgamegeek.com/boardgame/175324/fog-of-love'),
  ('Pictionary', 'base', 'https://boardgamegeek.com/boardgame/2281/pictionary'),
  ('Mastermind', 'base', 'https://boardgamegeek.com/boardgame/2392/mastermind'),
  ('Mage Knight: Ultimate Edition', 'base', 'https://boardgamegeek.com/boardgame/248562/mage-knight-ultimate-edition'),
  ('Rise of Augustus', 'base', 'https://boardgamegeek.com/boardgame/137297/rise-of-augustus'),
  ('Fearsome Floors', 'base', 'https://boardgamegeek.com/boardgame/7805/fearsome-floors'),
  ('Dungeon Roll', 'base', 'https://boardgamegeek.com/boardgame/138788/dungeon-roll'),
  ('Terraforming Mars: Colonies', 'expansion', 'https://boardgamegeek.com/boardgame/255681/terraforming-mars-colonies'),
  ('Trivial Pursuit: Genus Edition', 'base', 'https://boardgamegeek.com/boardgame/2952/trivial-pursuit-genus-edition'),
  ('TransAmerica', 'base', 'https://boardgamegeek.com/boardgame/2842/transamerica'),
  ('Rivals for Catan', 'base', 'https://boardgamegeek.com/boardgame/66056/rivals-for-catan'),
  ('Jambo', 'base', 'https://boardgamegeek.com/boardgame/12002/jambo'),
  ('Pirate''s Cove', 'base', 'https://boardgamegeek.com/boardgame/2987/pirates-cove'),
  ('Mystery of the Abbey', 'base', 'https://boardgamegeek.com/boardgame/915/mystery-of-the-abbey'),
  ('Abalone', 'base', 'https://boardgamegeek.com/boardgame/526/abalone'),
  ('Scythe: The Rise of Fenris', 'expansion', 'https://boardgamegeek.com/boardgame/242277/scythe-the-rise-of-fenris'),
  ('Virus!', 'base', 'https://boardgamegeek.com/boardgame/180020/virus'),
  ('Mahjong', 'base', 'https://boardgamegeek.com/boardgame/2093/mahjong'),
  ('NMBR 9', 'base', 'https://boardgamegeek.com/boardgame/217449/nmbr-9'),
  ('Dominoes', 'base', 'https://boardgamegeek.com/boardgame/2394/dominoes'),
  ('Runebound: Second Edition', 'base', 'https://boardgamegeek.com/boardgame/21523/runebound-second-edition'),
  ('Dice Town', 'base', 'https://boardgamegeek.com/boardgame/40793/dice-town'),
  ('Red November', 'base', 'https://boardgamegeek.com/boardgame/36946/red-november'),
  ('Cartagena', 'base', 'https://boardgamegeek.com/boardgame/826/cartagena'),
  ('Kalah', 'base', 'https://boardgamegeek.com/boardgame/2448/kalah'),
  ('The Lost Expedition', 'base', 'https://boardgamegeek.com/boardgame/216459/the-lost-expedition'),
  ('Tiny Epic Quest', 'base', 'https://boardgamegeek.com/boardgame/201921/tiny-epic-quest'),
  ('Formula Dé', 'base', 'https://boardgamegeek.com/boardgame/173/formula-de'),
  ('DC Deck-Building Game', 'base', 'https://boardgamegeek.com/boardgame/125678/dc-deck-building-game'),
  ('Tiny Epic Kingdoms', 'base', 'https://boardgamegeek.com/boardgame/148951/tiny-epic-kingdoms'),
  ('Scythe: The Wind Gambit', 'expansion', 'https://boardgamegeek.com/boardgame/223555/scythe-the-wind-gambit'),
  ('Similo', 'base', 'https://boardgamegeek.com/boardgame/268620/similo'),
  ('Spirit Island: Branch & Claw', 'expansion', 'https://boardgamegeek.com/boardgame/193065/spirit-island-branch-and-claw'),
  ('Dream Home', 'base', 'https://boardgamegeek.com/boardgame/194880/dream-home'),
  ('Ticket to Ride: New York', 'base', 'https://boardgamegeek.com/boardgame/253284/ticket-to-ride-new-york'),
  ('Hues and Cues', 'base', 'https://boardgamegeek.com/boardgame/302520/hues-and-cues'),
  ('Tides of Time', 'base', 'https://boardgamegeek.com/boardgame/176229/tides-of-time'),
  ('Terror in Meeple City', 'base', 'https://boardgamegeek.com/boardgame/97903/terror-in-meeple-city'),
  ('Bandido', 'base', 'https://boardgamegeek.com/boardgame/191925/bandido'),
  ('Munchkin 2: Unnatural Axe', 'expansion', 'https://boardgamegeek.com/boardgame/3943/munchkin-2-unnatural-axe'),
  ('Sorry!', 'base', 'https://boardgamegeek.com/boardgame/2407/sorry'),
  ('Kill Doctor Lucky', 'base', 'https://boardgamegeek.com/boardgame/257/kill-doctor-lucky'),
  ('Dixit: Quest', 'expansion', 'https://boardgamegeek.com/boardgame/55660/dixit-quest'),
  ('Guess Who?', 'base', 'https://boardgamegeek.com/boardgame/4143/guess-who'),
  ('Hansa Teutonica: Big Box', 'base', 'https://boardgamegeek.com/boardgame/286749/hansa-teutonica-big-box'),
  ('Colossal Arena', 'base', 'https://boardgamegeek.com/boardgame/105/colossal-arena'),
  ('Among the Stars', 'base', 'https://boardgamegeek.com/boardgame/110277/among-the-stars'),
  ('Risk 2210 A.D.', 'base', 'https://boardgamegeek.com/boardgame/1829/risk-2210-ad'),
  ('Ark Nova: Marine Worlds', 'expansion', 'https://boardgamegeek.com/boardgame/368966/ark-nova-marine-worlds'),
  ('The Quacks of Quedlinburg: The Herb Witches', 'expansion', 'https://boardgamegeek.com/boardgame/269259/the-quacks-of-quedlinburg-the-herb-witches'),
  ('Room 25', 'base', 'https://boardgamegeek.com/boardgame/127024/room-25'),
  ('The Big Book of Madness', 'base', 'https://boardgamegeek.com/boardgame/171233/the-big-book-of-madness'),
  ('Adrenaline', 'base', 'https://boardgamegeek.com/boardgame/202408/adrenaline'),
  ('Loot', 'base', 'https://boardgamegeek.com/boardgame/770/loot'),
  ('Dungeon Fighter', 'base', 'https://boardgamegeek.com/boardgame/102548/dungeon-fighter'),
  ('The Castles of Burgundy: The Card Game', 'base', 'https://boardgamegeek.com/boardgame/191977/the-castles-of-burgundy-the-card-game'),
  ('Pass the Pigs', 'base', 'https://boardgamegeek.com/boardgame/2593/pass-the-pigs'),
  ('Catan Dice Game', 'base', 'https://boardgamegeek.com/boardgame/27710/catan-dice-game'),
  ('Cry Havoc', 'base', 'https://boardgamegeek.com/boardgame/192457/cry-havoc'),
  ('Epic Spell Wars of the Battle Wizards: Duel at Mt. Skullzfyre', 'base', 'https://boardgamegeek.com/boardgame/112686/epic-spell-wars-of-the-battle-wizards-duel-at-mt-s'),
  ('Eldritch Horror: Forsaken Lore', 'expansion', 'https://boardgamegeek.com/boardgame/154842/eldritch-horror-forsaken-lore'),
  ('Palm Island', 'base', 'https://boardgamegeek.com/boardgame/239464/palm-island'),
  ('Blueprints', 'base', 'https://boardgamegeek.com/boardgame/140933/blueprints'),
  ('Call to Adventure', 'base', 'https://boardgamegeek.com/boardgame/238992/call-to-adventure'),
  ('Get Bit!', 'base', 'https://boardgamegeek.com/boardgame/30539/get-bit'),
  ('Mint Works', 'base', 'https://boardgamegeek.com/boardgame/200077/mint-works'),
  ('Cat Lady', 'base', 'https://boardgamegeek.com/boardgame/228504/cat-lady'),
  ('Happy Salmon', 'base', 'https://boardgamegeek.com/boardgame/194626/happy-salmon'),
  ('Jaws', 'base', 'https://boardgamegeek.com/boardgame/272738/jaws'),
  ('Tsuro of the Seas', 'base', 'https://boardgamegeek.com/boardgame/124172/tsuro-of-the-seas'),
  ('T.I.M.E Stories: The Marcy Case', 'expansion', 'https://boardgamegeek.com/boardgame/180585/time-stories-the-marcy-case'),
  ('Keltis', 'base', 'https://boardgamegeek.com/boardgame/34585/keltis'),
  ('Dungeons & Dragons: Wrath of Ashardalon Board Game', 'base', 'https://boardgamegeek.com/boardgame/66356/dungeons-and-dragons-wrath-of-ashardalon-board-gam'),
  ('Zombie Fluxx', 'base', 'https://boardgamegeek.com/boardgame/29387/zombie-fluxx'),
  ('That''s Not a Hat', 'base', 'https://boardgamegeek.com/boardgame/375651/thats-not-a-hat'),
  ('Citadels: The Dark City', 'expansion', 'https://boardgamegeek.com/boardgame/13291/citadels-the-dark-city'),
  ('Loony Quest', 'base', 'https://boardgamegeek.com/boardgame/136991/loony-quest'),
  ('Majesty: For the Realm', 'base', 'https://boardgamegeek.com/boardgame/230080/majesty-for-the-realm'),
  ('Skyjo', 'base', 'https://boardgamegeek.com/boardgame/204135/skyjo'),
  ('Ticket to Ride Map Collection 2: India & Switzerland', 'expansion', 'https://boardgamegeek.com/boardgame/106645/ticket-to-ride-map-collection-2-india-and-switzerl'),
  ('The Magic Labyrinth', 'base', 'https://boardgamegeek.com/boardgame/41916/the-magic-labyrinth'),
  ('Onirim', 'base', 'https://boardgamegeek.com/boardgame/71836/onirim'),
  ('Cleopatra and the Society of Architects', 'base', 'https://boardgamegeek.com/boardgame/22141/cleopatra-and-the-society-of-architects'),
  ('Metro', 'base', 'https://boardgamegeek.com/boardgame/559/metro'),
  ('Attika', 'base', 'https://boardgamegeek.com/boardgame/8051/attika'),
  ('Dominion: Dark Ages', 'expansion', 'https://boardgamegeek.com/boardgame/125403/dominion-dark-ages'),
  ('Joking Hazard', 'base', 'https://boardgamegeek.com/boardgame/193621/joking-hazard'),
  ('CV', 'base', 'https://boardgamegeek.com/boardgame/143986/cv'),
  ('Dungeons & Dragons: The Legend of Drizzt Board Game', 'base', 'https://boardgamegeek.com/boardgame/91872/dungeons-and-dragons-the-legend-of-drizzt-board-ga'),
  ('The Chameleon', 'base', 'https://boardgamegeek.com/boardgame/227072/the-chameleon'),
  ('Dominion: Hinterlands', 'expansion', 'https://boardgamegeek.com/boardgame/104557/dominion-hinterlands'),
  ('Balderdash', 'base', 'https://boardgamegeek.com/boardgame/163/balderdash'),
  ('Snow Tails', 'base', 'https://boardgamegeek.com/boardgame/38054/snow-tails'),
  ('Arkham Horror: Dunwich Horror Expansion', 'expansion', 'https://boardgamegeek.com/boardgame/21059/arkham-horror-dunwich-horror-expansion'),
  ('Cheating Moth', 'base', 'https://boardgamegeek.com/boardgame/105593/cheating-moth'),
  ('New York 1901', 'base', 'https://boardgamegeek.com/boardgame/174660/new-york-1901'),
  ('Mamma Mia!', 'base', 'https://boardgamegeek.com/boardgame/49/mamma-mia'),
  ('Fireball Island: The Curse of Vul-Kar', 'base', 'https://boardgamegeek.com/boardgame/233020/fireball-island-the-curse-of-vul-kar'),
  ('Lords of Xidit', 'base', 'https://boardgamegeek.com/boardgame/156566/lords-of-xidit'),
  ('Spyrium', 'base', 'https://boardgamegeek.com/boardgame/137269/spyrium'),
  ('Root: The Underworld Expansion', 'expansion', 'https://boardgamegeek.com/boardgame/272637/root-the-underworld-expansion'),
  ('Fabled Fruit', 'base', 'https://boardgamegeek.com/boardgame/203427/fabled-fruit'),
  ('Ticket to Ride Map Collection 1: Asia + Legendary Asia', 'expansion', 'https://boardgamegeek.com/boardgame/106637/ticket-to-ride-map-collection-1-asia-plus-legendar'),
  ('Manila', 'base', 'https://boardgamegeek.com/boardgame/15817/manila'),
  ('Say Anything', 'base', 'https://boardgamegeek.com/boardgame/33604/say-anything'),
  ('Meeple Circus', 'base', 'https://boardgamegeek.com/boardgame/193214/meeple-circus'),
  ('A Game of Thrones: The Card Game', 'base', 'https://boardgamegeek.com/boardgame/39953/a-game-of-thrones-the-card-game'),
  ('Abandon All Artichokes', 'base', 'https://boardgamegeek.com/boardgame/302260/abandon-all-artichokes'),
  ('The Grimm Forest', 'base', 'https://boardgamegeek.com/boardgame/212402/the-grimm-forest'),
  ('Carcassonne: Towers & Thieves', 'expansion', 'https://boardgamegeek.com/boardgame/21385/carcassonne-towers-and-thieves'),
  ('Dead Man''s Draw', 'base', 'https://boardgamegeek.com/boardgame/149155/dead-mans-draw'),
  ('Werewords', 'base', 'https://boardgamegeek.com/boardgame/219215/werewords'),
  ('Ticket to Ride Map Collection 5: United Kingdom & Pennsylvania', 'expansion', 'https://boardgamegeek.com/boardgame/182078/ticket-to-ride-map-collection-5-united-kingdom-and'),
  ('Hostage Negotiator', 'base', 'https://boardgamegeek.com/boardgame/134253/hostage-negotiator'),
  ('Two Rooms and a Boom', 'base', 'https://boardgamegeek.com/boardgame/134352/two-rooms-and-a-boom'),
  ('Spirit Island: Jagged Earth', 'expansion', 'https://boardgamegeek.com/boardgame/262722/spirit-island-jagged-earth'),
  ('Herbaceous', 'base', 'https://boardgamegeek.com/boardgame/195314/herbaceous'),
  ('Genoa', 'base', 'https://boardgamegeek.com/boardgame/1345/genoa'),
  ('Rattus', 'base', 'https://boardgamegeek.com/boardgame/42452/rattus'),
  ('Dominion: Cornucopia', 'expansion', 'https://boardgamegeek.com/boardgame/90850/dominion-cornucopia'),
  ('Planet', 'base', 'https://boardgamegeek.com/boardgame/252929/planet'),
  ('When I Dream', 'base', 'https://boardgamegeek.com/boardgame/198454/when-i-dream'),
  ('Kodama: The Tree Spirits', 'base', 'https://boardgamegeek.com/boardgame/181810/kodama-the-tree-spirits'),
  ('Ticket to Ride: Europa 1912', 'expansion', 'https://boardgamegeek.com/boardgame/53383/ticket-to-ride-europa-1912'),
  ('Pachisi', 'base', 'https://boardgamegeek.com/boardgame/2136/pachisi'),
  ('Marrakech', 'base', 'https://boardgamegeek.com/boardgame/29223/marrakech'),
  ('Machi Koro: Harbor', 'expansion', 'https://boardgamegeek.com/boardgame/143789/machi-koro-harbor'),
  ('Balloon Cup', 'base', 'https://boardgamegeek.com/boardgame/5716/balloon-cup'),
  ('Dale of Merchants', 'base', 'https://boardgamegeek.com/boardgame/176165/dale-of-merchants'),
  ('Tiny Epic Zombies', 'base', 'https://boardgamegeek.com/boardgame/244536/tiny-epic-zombies'),
  ('Power Grid: Factory Manager', 'base', 'https://boardgamegeek.com/boardgame/44163/power-grid-factory-manager'),
  ('Dungeon Twister', 'base', 'https://boardgamegeek.com/boardgame/12995/dungeon-twister'),
  ('Steam Park', 'base', 'https://boardgamegeek.com/boardgame/121410/steam-park'),
  ('Blokus Duo', 'base', 'https://boardgamegeek.com/boardgame/16395/blokus-duo'),
  ('Coup: Reformation', 'expansion', 'https://boardgamegeek.com/boardgame/148931/coup-reformation'),
  ('Race for the Galaxy: Rebel vs Imperium', 'expansion', 'https://boardgamegeek.com/boardgame/40210/race-for-the-galaxy-rebel-vs-imperium'),
  ('Nightmare Productions', 'base', 'https://boardgamegeek.com/boardgame/904/nightmare-productions'),
  ('Manhattan', 'base', 'https://boardgamegeek.com/boardgame/199/manhattan'),
  ('Battlestar Galactica: The Board Game – Pegasus Expansion', 'expansion', 'https://boardgamegeek.com/boardgame/43539/battlestar-galactica-the-board-game-pegasus-expans'),
  ('Encore!', 'base', 'https://boardgamegeek.com/boardgame/206931/encore'),
  ('Killer Bunnies and the Quest for the Magic Carrot', 'base', 'https://boardgamegeek.com/boardgame/3699/killer-bunnies-and-the-quest-for-the-magic-carrot'),
  ('World of Warcraft: The Boardgame', 'base', 'https://boardgamegeek.com/boardgame/17223/world-of-warcraft-the-boardgame'),
  ('Agricola: Farmers of the Moor', 'expansion', 'https://boardgamegeek.com/boardgame/43018/agricola-farmers-of-the-moor'),
  ('Winner''s Circle', 'base', 'https://boardgamegeek.com/boardgame/1382/winners-circle'),
  ('Junta', 'base', 'https://boardgamegeek.com/boardgame/242/junta'),
  ('Star Fluxx', 'base', 'https://boardgamegeek.com/boardgame/102104/star-fluxx'),
  ('Small World: Cursed!', 'expansion', 'https://boardgamegeek.com/boardgame/57072/small-world-cursed'),
  ('Anomia', 'base', 'https://boardgamegeek.com/boardgame/67877/anomia'),
  ('On Tour', 'base', 'https://boardgamegeek.com/boardgame/251412/on-tour'),
  ('7 Wonders Duel: Agora', 'expansion', 'https://boardgamegeek.com/boardgame/309116/7-wonders-duel-agora'),
  ('Linko', 'base', 'https://boardgamegeek.com/boardgame/153065/linko'),
  ('Star Wars: The Card Game', 'base', 'https://boardgamegeek.com/boardgame/103886/star-wars-the-card-game'),
  ('Nations: The Dice Game', 'base', 'https://boardgamegeek.com/boardgame/157809/nations-the-dice-game'),
  ('Saboteur 2 (expansion-only editions)', 'expansion', 'https://boardgamegeek.com/boardgame/91072/saboteur-2-expansion-only-editions'),
  ('La Isla', 'base', 'https://boardgamegeek.com/boardgame/154246/la-isla'),
  ('Blue Moon', 'base', 'https://boardgamegeek.com/boardgame/9446/blue-moon'),
  ('Claim', 'base', 'https://boardgamegeek.com/boardgame/233961/claim'),
  ('Ticket to Ride: London', 'base', 'https://boardgamegeek.com/boardgame/276894/ticket-to-ride-london'),
  ('Small World: Grand Dames of Small World', 'expansion', 'https://boardgamegeek.com/boardgame/57070/small-world-grand-dames-of-small-world'),
  ('Viceroy', 'base', 'https://boardgamegeek.com/boardgame/157526/viceroy'),
  ('Diamonds', 'base', 'https://boardgamegeek.com/boardgame/152162/diamonds'),
  ('Terraforming Mars: Turmoil', 'expansion', 'https://boardgamegeek.com/boardgame/273473/terraforming-mars-turmoil'),
  ('Black Fleet', 'base', 'https://boardgamegeek.com/boardgame/157403/black-fleet'),
  ('Battle Sheep', 'base', 'https://boardgamegeek.com/boardgame/54137/battle-sheep'),
  ('Fugitive', 'base', 'https://boardgamegeek.com/boardgame/197443/fugitive'),
  ('Mariposas', 'base', 'https://boardgamegeek.com/boardgame/297978/mariposas'),
  ('Talisman', 'base', 'https://boardgamegeek.com/boardgame/714/talisman'),
  ('Pandemic: In the Lab', 'expansion', 'https://boardgamegeek.com/boardgame/137136/pandemic-in-the-lab'),
  ('Mountain Goats', 'base', 'https://boardgamegeek.com/boardgame/63975/mountain-goats'),
  ('7 Wonders: Wonder Pack', 'expansion', 'https://boardgamegeek.com/boardgame/133993/7-wonders-wonder-pack'),
  ('Mysterium Park', 'base', 'https://boardgamegeek.com/boardgame/301767/mysterium-park'),
  ('Munchkin Cthulhu', 'base', 'https://boardgamegeek.com/boardgame/25071/munchkin-cthulhu'),
  ('Marvel Dice Masters: Avengers vs. X-Men', 'base', 'https://boardgamegeek.com/boardgame/148575/marvel-dice-masters-avengers-vs-x-men'),
  ('Outfoxed!', 'base', 'https://boardgamegeek.com/boardgame/172931/outfoxed'),
  ('Scoville', 'base', 'https://boardgamegeek.com/boardgame/145659/scoville'),
  ('Illusion', 'base', 'https://boardgamegeek.com/boardgame/244995/illusion'),
  ('Chrononauts', 'base', 'https://boardgamegeek.com/boardgame/815/chrononauts'),
  ('Letter Jam', 'base', 'https://boardgamegeek.com/boardgame/275467/letter-jam'),
  ('Ticket to Ride: 10th Anniversary', 'base', 'https://boardgamegeek.com/boardgame/160069/ticket-to-ride-10th-anniversary'),
  ('Carcassonne: Abbey & Mayor', 'expansion', 'https://boardgamegeek.com/boardgame/31784/carcassonne-abbey-and-mayor'),
  ('Paper Tales', 'base', 'https://boardgamegeek.com/boardgame/217861/paper-tales'),
  ('Twister', 'base', 'https://boardgamegeek.com/boardgame/5894/twister'),
  ('Monty Python Fluxx', 'base', 'https://boardgamegeek.com/boardgame/36345/monty-python-fluxx'),
  ('Small World: Be Not Afraid...', 'expansion', 'https://boardgamegeek.com/boardgame/81618/small-world-be-not-afraid'),
  ('Jekyll vs. Hyde', 'base', 'https://boardgamegeek.com/boardgame/297129/jekyll-vs-hyde'),
  ('Exploding Kittens: Imploding Kittens', 'expansion', 'https://boardgamegeek.com/boardgame/204053/exploding-kittens-imploding-kittens'),
  ('Louis XIV', 'base', 'https://boardgamegeek.com/boardgame/13642/louis-xiv'),
  ('Hoity Toity', 'base', 'https://boardgamegeek.com/boardgame/120/hoity-toity'),
  ('T.I.M.E Stories: A Prophecy of Dragons', 'expansion', 'https://boardgamegeek.com/boardgame/189035/time-stories-a-prophecy-of-dragons'),
  ('Tajemnicze Domostwo', 'base', 'https://boardgamegeek.com/boardgame/113997/tajemnicze-domostwo'),
  ('Coffee Rush', 'base', 'https://boardgamegeek.com/boardgame/377061/coffee-rush'),
  ('Chinese Checkers', 'base', 'https://boardgamegeek.com/boardgame/2386/chinese-checkers'),
  ('Catan: Traders & Barbarians', 'expansion', 'https://boardgamegeek.com/boardgame/27760/catan-traders-and-barbarians'),
  ('Munchkin 3: Clerical Errors', 'expansion', 'https://boardgamegeek.com/boardgame/6606/munchkin-3-clerical-errors'),
  ('Strike', 'base', 'https://boardgamegeek.com/boardgame/123570/strike'),
  ('Unearth', 'base', 'https://boardgamegeek.com/boardgame/217085/unearth'),
  ('Black Stories', 'base', 'https://boardgamegeek.com/boardgame/18803/black-stories'),
  ('Jump Drive', 'base', 'https://boardgamegeek.com/boardgame/205597/jump-drive'),
  ('The Starfarers of Catan', 'base', 'https://boardgamegeek.com/boardgame/1897/the-starfarers-of-catan'),
  ('Dice City', 'base', 'https://boardgamegeek.com/boardgame/179572/dice-city'),
  ('Bears vs Babies', 'base', 'https://boardgamegeek.com/boardgame/211534/bears-vs-babies'),
  ('Fleet', 'base', 'https://boardgamegeek.com/boardgame/121297/fleet'),
  ('Cosmolancer', 'base', 'https://boardgamegeek.com/boardgame/119/cosmolancer'),
  ('Legendary: A Marvel Deck Building Game – Dark City', 'expansion', 'https://boardgamegeek.com/boardgame/137762/legendary-a-marvel-deck-building-game-dark-city'),
  ('Sleeping Queens', 'base', 'https://boardgamegeek.com/boardgame/17053/sleeping-queens'),
  ('Eight-Minute Empire: Legends', 'base', 'https://boardgamegeek.com/boardgame/142326/eight-minute-empire-legends'),
  ('Escape from the Aliens in Outer Space', 'base', 'https://boardgamegeek.com/boardgame/82168/escape-from-the-aliens-in-outer-space'),
  ('Ikusa', 'base', 'https://boardgamegeek.com/boardgame/221/ikusa'),
  ('Candy Land', 'base', 'https://boardgamegeek.com/boardgame/5048/candy-land'),
  ('Pokémon Trading Card Game', 'base', 'https://boardgamegeek.com/boardgame/2165/pokemon-trading-card-game'),
  ('Clans', 'base', 'https://boardgamegeek.com/boardgame/4636/clans'),
  ('Honshū', 'base', 'https://boardgamegeek.com/boardgame/207336/honshu'),
  ('Istanbul: The Dice Game', 'base', 'https://boardgamegeek.com/boardgame/235488/istanbul-the-dice-game'),
  ('La Città', 'base', 'https://boardgamegeek.com/boardgame/554/la-citta'),
  ('Harbour', 'base', 'https://boardgamegeek.com/boardgame/155969/harbour'),
  ('Dragonwood', 'base', 'https://boardgamegeek.com/boardgame/172933/dragonwood'),
  ('Star Wars: Rebellion – Rise of the Empire', 'expansion', 'https://boardgamegeek.com/boardgame/226840/star-wars-rebellion-rise-of-the-empire'),
  ('Hansa', 'base', 'https://boardgamegeek.com/boardgame/8989/hansa'),
  ('Illuminati', 'base', 'https://boardgamegeek.com/boardgame/28/illuminati'),
  ('Carcassonne Big Box 6', 'base', 'https://boardgamegeek.com/boardgame/230914/carcassonne-big-box-6'),
  ('Ligretto', 'base', 'https://boardgamegeek.com/boardgame/943/ligretto'),
  ('Black Angel', 'base', 'https://boardgamegeek.com/boardgame/230244/black-angel'),
  ('Reef Encounter', 'base', 'https://boardgamegeek.com/boardgame/12962/reef-encounter'),
  ('Turn the Tide', 'base', 'https://boardgamegeek.com/boardgame/1403/turn-the-tide'),
  ('Tussie Mussie', 'base', 'https://boardgamegeek.com/boardgame/257614/tussie-mussie'),
  ('Chutes and Ladders', 'base', 'https://boardgamegeek.com/boardgame/5432/chutes-and-ladders'),
  ('Doom: The Boardgame', 'base', 'https://boardgamegeek.com/boardgame/10640/doom-the-boardgame'),
  ('The Speicherstadt', 'base', 'https://boardgamegeek.com/boardgame/66505/the-speicherstadt'),
  ('Timeline: Events', 'base', 'https://boardgamegeek.com/boardgame/113401/timeline-events'),
  ('Oriflamme', 'base', 'https://boardgamegeek.com/boardgame/287084/oriflamme'),
  ('Luxor', 'base', 'https://boardgamegeek.com/boardgame/245643/luxor'),
  ('Wiz-War (Eighth Edition)', 'base', 'https://boardgamegeek.com/boardgame/104710/wiz-war-eighth-edition'),
  ('Maharaja: The Game of Palace Building in India', 'base', 'https://boardgamegeek.com/boardgame/9440/maharaja-the-game-of-palace-building-in-india'),
  ('Star Munchkin', 'base', 'https://boardgamegeek.com/boardgame/4095/star-munchkin'),
  ('Dune: Imperium – Immortality', 'expansion', 'https://boardgamegeek.com/boardgame/367466/dune-imperium-immortality'),
  ('Istanbul: Big Box', 'base', 'https://boardgamegeek.com/boardgame/251219/istanbul-big-box'),
  ('Felicity: The Cat in the Sack', 'base', 'https://boardgamegeek.com/boardgame/32125/felicity-the-cat-in-the-sack'),
  ('Hyperborea', 'base', 'https://boardgamegeek.com/boardgame/119788/hyperborea'),
  ('Cutthroat Caverns', 'base', 'https://boardgamegeek.com/boardgame/28259/cutthroat-caverns'),
  ('boop.', 'base', 'https://boardgamegeek.com/boardgame/355433/boop'),
  ('King of Tokyo: Halloween', 'expansion', 'https://boardgamegeek.com/boardgame/147183/king-of-tokyo-halloween'),
  ('Discoveries: The Journals of Lewis & Clark', 'base', 'https://boardgamegeek.com/boardgame/171669/discoveries-the-journals-of-lewis-and-clark'),
  ('Splendor: Cities of Splendor', 'expansion', 'https://boardgamegeek.com/boardgame/220653/splendor-cities-of-splendor'),
  ('Insider', 'base', 'https://boardgamegeek.com/boardgame/206051/insider'),
  ('Throw Throw Burrito', 'base', 'https://boardgamegeek.com/boardgame/274533/throw-throw-burrito'),
  ('Dutch Blitz', 'base', 'https://boardgamegeek.com/boardgame/148203/dutch-blitz'),
  ('Ave Caesar', 'base', 'https://boardgamegeek.com/boardgame/494/ave-caesar'),
  ('Ticket to Ride: Switzerland', 'expansion', 'https://boardgamegeek.com/boardgame/30746/ticket-to-ride-switzerland'),
  ('Risk: The Lord of the Rings', 'base', 'https://boardgamegeek.com/boardgame/4324/risk-the-lord-of-the-rings'),
  ('Samurai Spirit', 'base', 'https://boardgamegeek.com/boardgame/158900/samurai-spirit'),
  ('Hearts', 'base', 'https://boardgamegeek.com/boardgame/6887/hearts'),
  ('Rolling Realms', 'base', 'https://boardgamegeek.com/boardgame/305682/rolling-realms'),
  ('Valley of the Kings', 'base', 'https://boardgamegeek.com/boardgame/150999/valley-of-the-kings'),
  ('Container', 'base', 'https://boardgamegeek.com/boardgame/26990/container'),
  ('Everdell: Bellfaire', 'expansion', 'https://boardgamegeek.com/boardgame/289057/everdell-bellfaire'),
  ('Caylus Magna Carta', 'base', 'https://boardgamegeek.com/boardgame/27364/caylus-magna-carta'),
  ('Epic Card Game', 'base', 'https://boardgamegeek.com/boardgame/175621/epic-card-game'),
  ('Akrotiri', 'base', 'https://boardgamegeek.com/boardgame/154458/akrotiri'),
  ('Santa Monica', 'base', 'https://boardgamegeek.com/boardgame/298065/santa-monica'),
  ('Hare & Tortoise', 'base', 'https://boardgamegeek.com/boardgame/361/hare-and-tortoise'),
  ('Haggis', 'base', 'https://boardgamegeek.com/boardgame/37628/haggis'),
  ('Fauna', 'base', 'https://boardgamegeek.com/boardgame/35497/fauna'),
  ('Lost Cities: The Board Game', 'base', 'https://boardgamegeek.com/boardgame/42487/lost-cities-the-board-game'),
  ('Werewolf', 'base', 'https://boardgamegeek.com/boardgame/925/werewolf'),
  ('Outlive', 'base', 'https://boardgamegeek.com/boardgame/191051/outlive'),
  ('Massive Darkness', 'base', 'https://boardgamegeek.com/boardgame/197070/massive-darkness'),
  ('Botswana', 'base', 'https://boardgamegeek.com/boardgame/398/botswana'),
  ('The Palaces of Carrara', 'base', 'https://boardgamegeek.com/boardgame/129948/the-palaces-of-carrara'),
  ('The Adventurers: The Temple of Chac', 'base', 'https://boardgamegeek.com/boardgame/43868/the-adventurers-the-temple-of-chac'),
  ('Cross Clues', 'base', 'https://boardgamegeek.com/boardgame/300753/cross-clues'),
  ('Cockroach Poker Royal', 'base', 'https://boardgamegeek.com/boardgame/129736/cockroach-poker-royal'),
  ('Operation', 'base', 'https://boardgamegeek.com/boardgame/3737/operation'),
  ('Wasabi!', 'base', 'https://boardgamegeek.com/boardgame/33154/wasabi'),
  ('My First Carcassonne', 'base', 'https://boardgamegeek.com/boardgame/41010/my-first-carcassonne'),
  ('Super Mega Lucky Box', 'base', 'https://boardgamegeek.com/boardgame/341530/super-mega-lucky-box'),
  ('Zombicide Season 2: Prison Outbreak', 'base', 'https://boardgamegeek.com/boardgame/137988/zombicide-season-2-prison-outbreak'),
  ('Tragedy Looper', 'base', 'https://boardgamegeek.com/boardgame/148319/tragedy-looper'),
  ('Roll Player: Monsters & Minions', 'expansion', 'https://boardgamegeek.com/boardgame/213360/roll-player-monsters-and-minions'),
  ('Point City', 'base', 'https://boardgamegeek.com/boardgame/368017/point-city'),
  ('Ticket to Ride: Europe – 15th Anniversary', 'base', 'https://boardgamegeek.com/boardgame/329841/ticket-to-ride-europe-15th-anniversary'),
  ('Via Nebula', 'base', 'https://boardgamegeek.com/boardgame/191231/via-nebula'),
  ('Everdell: Pearlbrook', 'expansion', 'https://boardgamegeek.com/boardgame/259996/everdell-pearlbrook'),
  ('Caesar & Cleopatra', 'base', 'https://boardgamegeek.com/boardgame/132/caesar-and-cleopatra'),
  ('Betrayal at Baldur''s Gate', 'base', 'https://boardgamegeek.com/boardgame/228660/betrayal-at-baldurs-gate'),
  ('Ecos: First Continent', 'base', 'https://boardgamegeek.com/boardgame/279254/ecos-first-continent'),
  ('Betrayal at House on the Hill: Widow''s Walk', 'expansion', 'https://boardgamegeek.com/boardgame/198452/betrayal-at-house-on-the-hill-widows-walk'),
  ('Coconuts', 'base', 'https://boardgamegeek.com/boardgame/145639/coconuts'),
  ('Welcome Back to the Dungeon', 'base', 'https://boardgamegeek.com/boardgame/195043/welcome-back-to-the-dungeon'),
  ('Alhambra: Big Box', 'base', 'https://boardgamegeek.com/boardgame/45358/alhambra-big-box'),
  ('Little Town', 'base', 'https://boardgamegeek.com/boardgame/241266/little-town'),
  ('A Touch of Evil: The Supernatural Game', 'base', 'https://boardgamegeek.com/boardgame/35815/a-touch-of-evil-the-supernatural-game'),
  ('Roma', 'base', 'https://boardgamegeek.com/boardgame/16496/roma'),
  ('Hit Z Road', 'base', 'https://boardgamegeek.com/boardgame/176083/hit-z-road'),
  ('Primordial Soup', 'base', 'https://boardgamegeek.com/boardgame/124/primordial-soup'),
  ('Wings of War: Famous Aces', 'base', 'https://boardgamegeek.com/boardgame/9203/wings-of-war-famous-aces'),
  ('Clank!: Sunken Treasures', 'expansion', 'https://boardgamegeek.com/boardgame/218103/clank-sunken-treasures'),
  ('Beasty Bar', 'base', 'https://boardgamegeek.com/boardgame/165950/beasty-bar'),
  ('The Builders: Middle Ages', 'base', 'https://boardgamegeek.com/boardgame/144553/the-builders-middle-ages'),
  ('Antike', 'base', 'https://boardgamegeek.com/boardgame/19600/antike'),
  ('A Game of Thrones: Hand of the King', 'base', 'https://boardgamegeek.com/boardgame/205610/a-game-of-thrones-hand-of-the-king'),
  ('Imagine', 'base', 'https://boardgamegeek.com/boardgame/191894/imagine'),
  ('Dungeon Mayhem', 'base', 'https://boardgamegeek.com/boardgame/260300/dungeon-mayhem'),
  ('The Wolves', 'base', 'https://boardgamegeek.com/boardgame/368058/the-wolves'),
  ('Sushi Roll', 'base', 'https://boardgamegeek.com/boardgame/271869/sushi-roll'),
  ('Tribune: Primus Inter Pares', 'base', 'https://boardgamegeek.com/boardgame/30957/tribune-primus-inter-pares'),
  ('Ohanami', 'base', 'https://boardgamegeek.com/boardgame/270314/ohanami'),
  ('Santiago de Cuba', 'base', 'https://boardgamegeek.com/boardgame/104347/santiago-de-cuba'),
  ('13 Days: The Cuban Missile Crisis, 1962', 'base', 'https://boardgamegeek.com/boardgame/177590/13-days-the-cuban-missile-crisis-1962'),
  ('You''re Bluffing!', 'base', 'https://boardgamegeek.com/boardgame/1117/youre-bluffing'),
  ('Roam', 'base', 'https://boardgamegeek.com/boardgame/267319/roam'),
  ('Small World of Warcraft', 'base', 'https://boardgamegeek.com/boardgame/309630/small-world-of-warcraft'),
  ('Twilight Imperium: Third Edition – Shattered Empire', 'expansion', 'https://boardgamegeek.com/boardgame/22821/twilight-imperium-third-edition-shattered-empire'),
  ('A Feast for Odin: The Norwegians', 'expansion', 'https://boardgamegeek.com/boardgame/216788/a-feast-for-odin-the-norwegians'),
  ('San Marco', 'base', 'https://boardgamegeek.com/boardgame/1041/san-marco'),
  ('Hawaii', 'base', 'https://boardgamegeek.com/boardgame/106217/hawaii'),
  ('Dark Souls: The Board Game', 'base', 'https://boardgamegeek.com/boardgame/197831/dark-souls-the-board-game'),
  ('Rallyman: GT', 'base', 'https://boardgamegeek.com/boardgame/256589/rallyman-gt'),
  ('Courtisans', 'base', 'https://boardgamegeek.com/boardgame/402283/courtisans'),
  ('Vasco da Gama', 'base', 'https://boardgamegeek.com/boardgame/41002/vasco-da-gama'),
  ('Mottainai', 'base', 'https://boardgamegeek.com/boardgame/175199/mottainai'),
  ('Odin''s Ravens (Second Edition)', 'base', 'https://boardgamegeek.com/boardgame/192074/odins-ravens-second-edition'),
  ('BANG! Dodge City', 'expansion', 'https://boardgamegeek.com/boardgame/9653/bang-dodge-city'),
  ('History of the World', 'base', 'https://boardgamegeek.com/boardgame/224/history-of-the-world'),
  ('Trails', 'base', 'https://boardgamegeek.com/boardgame/338628/trails'),
  ('Domaine', 'base', 'https://boardgamegeek.com/boardgame/5737/domaine'),
  ('Obscurio', 'base', 'https://boardgamegeek.com/boardgame/273477/obscurio'),
  ('Tammany Hall', 'base', 'https://boardgamegeek.com/boardgame/30645/tammany-hall'),
  ('Archaeology: The New Expedition', 'base', 'https://boardgamegeek.com/boardgame/191300/archaeology-the-new-expedition'),
  ('Trouble', 'base', 'https://boardgamegeek.com/boardgame/1410/trouble'),
  ('Mafia de Cuba', 'base', 'https://boardgamegeek.com/boardgame/176558/mafia-de-cuba'),
  ('Concordia: Salsa', 'expansion', 'https://boardgamegeek.com/boardgame/181084/concordia-salsa'),
  ('Catan: Seafarers – 5-6 Player Extension', 'expansion', 'https://boardgamegeek.com/boardgame/4103/catan-seafarers-5-6-player-extension'),
  ('Carcassonne: The City', 'base', 'https://boardgamegeek.com/boardgame/12902/carcassonne-the-city'),
  ('Rune Age', 'base', 'https://boardgamegeek.com/boardgame/94362/rune-age'),
  ('Rex: Final Days of an Empire', 'base', 'https://boardgamegeek.com/boardgame/104363/rex-final-days-of-an-empire'),
  ('Chez Geek', 'base', 'https://boardgamegeek.com/boardgame/553/chez-geek'),
  ('China', 'base', 'https://boardgamegeek.com/boardgame/18100/china'),
  ('Trial by Trolley', 'base', 'https://boardgamegeek.com/boardgame/282171/trial-by-trolley'),
  ('Terraforming Mars: The Dice Game', 'base', 'https://boardgamegeek.com/boardgame/296108/terraforming-mars-the-dice-game'),
  ('Starship Catan', 'base', 'https://boardgamegeek.com/boardgame/2338/starship-catan'),
  ('Terra Mystica: Fire & Ice', 'expansion', 'https://boardgamegeek.com/boardgame/161317/terra-mystica-fire-and-ice'),
  ('ZÈRTZ', 'base', 'https://boardgamegeek.com/boardgame/528/zertz'),
  ('Takenoko: Chibis', 'expansion', 'https://boardgamegeek.com/boardgame/174095/takenoko-chibis'),
  ('Brew', 'base', 'https://boardgamegeek.com/boardgame/332386/brew'),
  ('Tang Garden', 'base', 'https://boardgamegeek.com/boardgame/252153/tang-garden'),
  ('Lucky Numbers', 'base', 'https://boardgamegeek.com/boardgame/118247/lucky-numbers'),
  ('Dinosaur World', 'base', 'https://boardgamegeek.com/boardgame/317457/dinosaur-world'),
  ('Dungeon!', 'base', 'https://boardgamegeek.com/boardgame/1339/dungeon'),
  ('Martian Dice', 'base', 'https://boardgamegeek.com/boardgame/99875/martian-dice'),
  ('Evo', 'base', 'https://boardgamegeek.com/boardgame/1159/evo'),
  ('Pixies', 'base', 'https://boardgamegeek.com/boardgame/411875/pixies'),
  ('Copenhagen', 'base', 'https://boardgamegeek.com/boardgame/269595/copenhagen'),
  ('Era: Medieval Age', 'base', 'https://boardgamegeek.com/boardgame/270971/era-medieval-age'),
  ('Risk: Star Wars Edition', 'base', 'https://boardgamegeek.com/boardgame/183880/risk-star-wars-edition'),
  ('Legacy: The Testament of Duke de Crecy', 'base', 'https://boardgamegeek.com/boardgame/52461/legacy-the-testament-of-duke-de-crecy'),
  ('Arkadia', 'base', 'https://boardgamegeek.com/boardgame/25643/arkadia'),
  ('Villa Paletti', 'base', 'https://boardgamegeek.com/boardgame/2596/villa-paletti'),
  ('Timeline: General Interest', 'base', 'https://boardgamegeek.com/boardgame/131325/timeline-general-interest'),
  ('Revolution!', 'base', 'https://boardgamegeek.com/boardgame/34887/revolution'),
  ('Qwinto', 'base', 'https://boardgamegeek.com/boardgame/183006/qwinto'),
  ('Kluster', 'base', 'https://boardgamegeek.com/boardgame/277458/kluster'),
  ('Five Crowns', 'base', 'https://boardgamegeek.com/boardgame/1472/five-crowns'),
  ('Poison', 'base', 'https://boardgamegeek.com/boardgame/17025/poison')
on conflict (name) do update
  set bgg_url  = excluded.bgg_url,
      category = excluded.category;
